### ISSUE TITLE
npm包丢失ts声明文件

### ISSUE THREAD

**Issue by hongfaqiu** [sherluok/binary-bmp#1]
npm包中的ts声明文件丢失
![image](https://github.com/sherluok/binary-bmp/assets/62411296/950e67d4-f8db-4d0a-bee3-601046a015ea)

**Comment by tzengyuxio** [comment]
難怪找不到 `fromCanvas`

**Comment by hongfaqiu** [comment]
> 難怪找不到 `fromCanvas`

是呀，可以直接拷贝代码到项目里。
rollup的打包配置有点问题，npm包只能等待作者修复了。

**Comment by sherluok** [comment]
已在 [V1.2.0](https://unpkg.com/browse/binary-bmp@1.2.0/) 解决。

```ts
import { Bitmap, Bits } from 'binary-bmp';

const uint8Array = Bitmap.fromCanvas(canvasElement).bits(Bits.GREY).uint8Array();
```

也可以直接导入 `fromCanvas` 函数，但已经标记废弃，下个版本移除：

```ts
import { fromCanvas, GREY } from 'binary-bmp';

const uint8Array = fromCanvas(GREY, canvasElement);
```

**Comment by hongfaqiu** [comment]
@sherluok 感谢大佬，太高效啦！
